"use strict";
var MatchExpression = require('./MatchExpression');

// Autogenerated by cport.py on 2013-09-17 14:37
var AtomicMatchExpression = module.exports = function AtomicMatchExpression(){
	base.call(this);
	this._matchType = 'ATOMIC';
}, klass = AtomicMatchExpression, base =  MatchExpression, proto = klass.prototype = Object.create(base.prototype, {constructor:{value:klass}});

/**
 *
 * Writes a debug string for this object
 * @method debugString
 * @param level
 *
 */
proto.debugString = function debugString(level) {
	// File: expression.cpp lines: 48-50
	return this._debugAddSpace( level ) + "$atomic\n";
};

/**
 *
 * checks if this expression is == to the other
 * @method equivalent
 * @param other
 *
 */
proto.equivalent = function equivalent(other) {
	// File: expression.h lines: 198-199
	return other._matchType == 'ATOMIC';
};

/**
 *
 * matches checks the input doc against the internal element path to see if it is a match
 * @method matches
 * @param doc
 *
 */
proto.matches = function matches(doc) {
	// File: expression.h lines: 184-185
	return true;
};

/**
 *
 * Check if the input element matches
 * @method matchesSingleElement
 * @param e
 *
 */
proto.matchesSingleElement = function matchesSingleElement(e) {
	// File: expression.h lines: 188-189
	return true;
};

/**
 *
 * clone this instance to a new one
 * @method shallowClone
 *
 */
proto.shallowClone = function shallowClone(){
	// File: expression.h lines: 192-193
	return new AtomicMatchExpression();
};
