"use strict"



// Autogenerated by cport.py on 2013-09-17 14:37
var BSONMatchableDocument = module.exports = function (){

}, klass = BSONMatchableDocument, base =  Object  , proto = klass.prototype = Object.create(base.prototype, {constructor:{value:klass}});


// File: matchable.h lines: 49-49
//         BSONObj _obj;

proto._obj = undefined;


// File: matchable.h lines: 49-49
//         BSONObj _obj;

proto._obj = undefined;





/**
 * 
 * This documentation was automatically generated. Please update when you touch this function.
 * @method BSONMatchableDocument
 * @param
 *
 */
proto.BSONMatchableDocument = function BSONMatchableDocument( /*  const BSONObj& obj  */ ){

// File: matchable.cpp lines: 28-29
//     BSONMatchableDocument::BSONMatchableDocument( const BSONObj& obj )
//         : _obj( obj ) {
//     }



}


/**
 * 
 * This documentation was automatically generated. Please update when you touch this function.
 * @method getIterator
 * @param
 *
 */
proto.getIterator = function getIterator( /*  const ElementPath& path  */ ){
// File: matchable.h lines: 44-45
//         virtual ElementIterator* getIterator( const ElementPath& path ) const {
//             return new BSONElementIterator( path, _obj );
//         }




}


/**
 * 
 * This documentation was automatically generated. Please update when you touch this function.
 * @method toBSON
 * @param
 *
 */
proto.toBSON = function toBSON( /*  */ ){
// File: matchable.h lines: 42-41
//         virtual BSONObj toBSON() const { return _obj; }




}


/**
 * 
 * This documentation was automatically generated. Please update when you touch this function.
 * @method ~BSONMatchableDocument
 * @param
 *
 */
proto.~BSONMatchableDocument = function ~BSONMatchableDocument( /*  */ ){

// File: matchable.cpp lines: 32-32
//     BSONMatchableDocument::~BSONMatchableDocument() {
//     }



}