"use strict";

// Autogenerated by cport.py on 2013-09-17 14:37
var Context = module.exports = function (){

}, klass = Context, base = Object, proto = klass.prototype = Object.create(base.prototype, {constructor:{value:klass}});

// File: path.h lines: 62-62
proto._arrayOffset = undefined;

// File: path.h lines: 61-61
proto._element = undefined;

// File: path.h lines: 63-63
proto._outerArray = undefined;

/**
 *
 * Return the _arrayOffset property
 * @method arrayOffset
 *
 */
proto.arrayOffset = function arrayOffset( ){
	// File: path.h lines: 57-56
	return this._arrayOffset;
};

/**
 *
 * Return the _element property
 * @method element
 *
 */
proto.element = function element( ){
	// File: path.h lines: 56-55
	return this._element;
};

/**
 *
 * Return the _outerArray property
 * @method outerArray
 *
 */
proto.outerArray = function outerArray( ){
	// File: path.h lines: 58-57
	return this._outerArray;
};

/**
 *
 * Set _element to a new empty object
 * @method reset
 *
 */
proto.reset = function reset(){
	// File: path.cpp lines: 37-38
	this._element = {};
};

/**
 *
 * Set _arrayOffset property to the input element
 * @method setArrayOffset
 * @param e
 *
 */
proto.setArrayOffset = function setArrayOffset(e){
	// File: path.h lines: 54-53
	this._arrayOffset = e;
};


