"use strict"



// Autogenerated by cport.py on 2013-09-17 14:37
var ElementIterator = module.exports = function (){

}, klass = ElementIterator, base =  Object  , proto = klass.prototype = Object.create(base.prototype, {constructor:{value:klass}});





/**
 * 
 * This documentation was automatically generated. Please update when you touch this function.
 * @method ~ElementIterator
 * @param
 *
 */
proto.~ElementIterator = function ~ElementIterator( /*  */ ){

// File: path.cpp lines: 34-34
//     ElementIterator::~ElementIterator(){
//     }



}