"use strict";

var ComparisonMatchExpression = require('./ComparisonMatchExpression');

// Autogenerated by cport.py on 2013-09-17 14:37
var EqualityMatchExpression = module.exports = function EqualityMatchExpression(){
	this._matchType = 'EQ';
}, klass = EqualityMatchExpression, base =  ComparisonMatchExpression, proto = klass.prototype = Object.create(base.prototype, {constructor:{value:klass}});

/**
 * 
 * This documentation was automatically generated. Please update when you touch this function.
 * @method shallowClone
 * @param
 *
 */
proto.shallowClone = function shallowClone( /*  */ ){
// File: expression_leaf.h lines: 98-101
	var e = new EqualityMatchExpression();
	e.init ( this.path(), this._rhs );
	return e;
};

