"use strict"



// Autogenerated by cport.py on 2013-09-17 14:37
var EqualityMatchExpression = module.exports = function (){

}, klass = EqualityMatchExpression, base =  Object  , proto = klass.prototype = Object.create(base.prototype, {constructor:{value:klass}});





/**
 * 
 * This documentation was automatically generated. Please update when you touch this function.
 * @method EqualityMatchExpression
 * @param
 *
 */
proto.EqualityMatchExpression = function EqualityMatchExpression( /*  EQ  */ ){
// File: expression_leaf.h lines: 97-96
//         EqualityMatchExpression() : ComparisonMatchExpression( EQ ){}




}


/**
 * 
 * This documentation was automatically generated. Please update when you touch this function.
 * @method shallowClone
 * @param
 *
 */
proto.shallowClone = function shallowClone( /*  */ ){
// File: expression_leaf.h lines: 98-101
//         virtual LeafMatchExpression* shallowClone() const {
//             ComparisonMatchExpression* e = new EqualityMatchExpression();
//             e->init( path(), _rhs  );
//             return e;
//         }




}