"use strict"



// Autogenerated by cport.py on 2013-09-17 14:37
var FalseMatchExpression = module.exports = function (){

}, klass = FalseMatchExpression, base =  Object  , proto = klass.prototype = Object.create(base.prototype, {constructor:{value:klass}});





/**
 * 
 * This documentation was automatically generated. Please update when you touch this function.
 * @method FalseMatchExpression
 * @param
 *
 */
proto.FalseMatchExpression = function FalseMatchExpression( /*  ALWAYS_FALSE  */ ){
// File: expression.h lines: 206-205
//         FalseMatchExpression() : MatchExpression( ALWAYS_FALSE ){}




}


/**
 * 
 * This documentation was automatically generated. Please update when you touch this function.
 * @method debugString
 * @param
 *
 */
proto.debugString = function debugString( /*  StringBuilder& debug, int level  */ ){

// File: expression.cpp lines: 53-55
//     void FalseMatchExpression::debugString( StringBuilder& debug, int level ) const {
//         _debugAddSpace( debug, level );
//         debug << "$false\n";
//     }



}


/**
 * 
 * This documentation was automatically generated. Please update when you touch this function.
 * @method equivalent
 * @param
 *
 */
proto.equivalent = function equivalent( /*  const MatchExpression* other  */ ){
// File: expression.h lines: 222-223
//         virtual bool equivalent( const MatchExpression* other ) const {
//             return other->matchType() == ALWAYS_FALSE;
//         }




}


/**
 * 
 * This documentation was automatically generated. Please update when you touch this function.
 * @method matches
 * @param
 *
 */
proto.matches = function matches( /*  const MatchableDocument* doc, MatchDetails* details = 0  */ ){
// File: expression.h lines: 208-209
//         virtual bool matches( const MatchableDocument* doc, MatchDetails* details = 0 ) const {
//             return false;
//         }




}


/**
 * 
 * This documentation was automatically generated. Please update when you touch this function.
 * @method matchesSingleElement
 * @param
 *
 */
proto.matchesSingleElement = function matchesSingleElement( /*  const BSONElement& e  */ ){
// File: expression.h lines: 212-213
//         virtual bool matchesSingleElement( const BSONElement& e ) const {
//             return false;
//         }




}


/**
 * 
 * This documentation was automatically generated. Please update when you touch this function.
 * @method shallowClone
 * @param
 *
 */
proto.shallowClone = function shallowClone( /*  */ ){
// File: expression.h lines: 216-217
//         virtual MatchExpression* shallowClone() const {
//             return new FalseMatchExpression();
//         }




}