"use strict";

var ComparisonMatchExpression = require('./ComparisonMatchExpression');

// Autogenerated by cport.py on 2013-09-17 14:37
var GTEMatchExpression = module.exports = function GTEMatchExpression(){
	base.call(this);
	this._matchType = 'GTE';
}, klass = GTEMatchExpression, base =  ComparisonMatchExpression, proto = klass.prototype = Object.create(base.prototype, {constructor:{value:klass}});

/**
 *
 * Return a new instance of this class, with fields set the same as ourself
 * @method shallowClone
 * @param
 *
 */
proto.shallowClone = function shallowClone( /*  */ ){
// File: expression_leaf.h lines: 141-144
	var e = new GTEMatchExpression();
	e.init( this.path(), this._rhs );
	return e;
};

