"use strict"



// Autogenerated by cport.py on 2013-09-17 14:37
var GTEMatchExpression = module.exports = function (){

}, klass = GTEMatchExpression, base =  Object  , proto = klass.prototype = Object.create(base.prototype, {constructor:{value:klass}});





/**
 * 
 * This documentation was automatically generated. Please update when you touch this function.
 * @method GTEMatchExpression
 * @param
 *
 */
proto.GTEMatchExpression = function GTEMatchExpression( /*  GTE  */ ){
// File: expression_leaf.h lines: 140-139
//         GTEMatchExpression() : ComparisonMatchExpression( GTE ){}




}


/**
 * 
 * This documentation was automatically generated. Please update when you touch this function.
 * @method shallowClone
 * @param
 *
 */
proto.shallowClone = function shallowClone( /*  */ ){
// File: expression_leaf.h lines: 141-144
//         virtual LeafMatchExpression* shallowClone() const {
//             ComparisonMatchExpression* e = new GTEMatchExpression();
//             e->init( path(), _rhs  );
//             return e;
//         }




}