"use strict"



// Autogenerated by cport.py on 2013-09-17 14:37
var GTMatchExpression = module.exports = function (){

}, klass = GTMatchExpression, base =  Object  , proto = klass.prototype = Object.create(base.prototype, {constructor:{value:klass}});





/**
 * 
 * This documentation was automatically generated. Please update when you touch this function.
 * @method GTMatchExpression
 * @param
 *
 */
proto.GTMatchExpression = function GTMatchExpression( /*  GT  */ ){
// File: expression_leaf.h lines: 129-128
//         GTMatchExpression() : ComparisonMatchExpression( GT ){}




}


/**
 * 
 * This documentation was automatically generated. Please update when you touch this function.
 * @method shallowClone
 * @param
 *
 */
proto.shallowClone = function shallowClone( /*  */ ){
// File: expression_leaf.h lines: 130-133
//         virtual LeafMatchExpression* shallowClone() const {
//             ComparisonMatchExpression* e = new GTMatchExpression();
//             e->init( path(), _rhs  );
//             return e;
//         }




}