"use strict";

var ComparisonMatchExpression = require('./ComparisonMatchExpression');

// Autogenerated by cport.py on 2013-09-17 14:37
var GTMatchExpression = module.exports = function GTMatchExpression(){
	this._matchType = 'GTE'
}, klass = GTMatchExpression, base =  Object  , proto = klass.prototype = Object.create(base.prototype, {constructor:{value:klass}});


/**
 * 
 * This documentation was automatically generated. Please update when you touch this function.
 * @method shallowClone
 * @param
 *
 */
proto.shallowClone = function shallowClone( /*  */ ){
// File: expression_leaf.h lines: 130-133
        var e = new GTMatchExpression();
	e.init( this.path(), this._rhs );
	return e;
};

