"use strict";

var ComparisonMatchExpression = require('./ComparisonMatchExpression.js');

// Autogenerated by cport.py on 2013-09-17 14:37
var GTMatchExpression = module.exports = function GTMatchExpression(){
	base.call(this);
	this._matchType = 'GT';
}, klass = GTMatchExpression, base = ComparisonMatchExpression, proto = klass.prototype = Object.create(base.prototype, {constructor:{value:klass}});


/**
 *
 * Return a new instance of this class, with fields set the same as ourself
 * @method shallowClone
 * @param
 *
 */
proto.shallowClone = function shallowClone( /* */ ){
	// File: expression_leaf.h lines: 130-133
	var e = new GTMatchExpression();
	e.init( this.path(), this._rhs );
	return e;
};

