"use strict"



// Autogenerated by cport.py on 2013-09-17 14:37
var LTEMatchExpression = module.exports = function (){

}, klass = LTEMatchExpression, base =  Object  , proto = klass.prototype = Object.create(base.prototype, {constructor:{value:klass}});





/**
 * 
 * This documentation was automatically generated. Please update when you touch this function.
 * @method LTEMatchExpression
 * @param
 *
 */
proto.LTEMatchExpression = function LTEMatchExpression( /*  LTE  */ ){
// File: expression_leaf.h lines: 107-106
//         LTEMatchExpression() : ComparisonMatchExpression( LTE ){}




}


/**
 * 
 * This documentation was automatically generated. Please update when you touch this function.
 * @method shallowClone
 * @param
 *
 */
proto.shallowClone = function shallowClone( /*  */ ){
// File: expression_leaf.h lines: 108-111
//         virtual LeafMatchExpression* shallowClone() const {
//             ComparisonMatchExpression* e = new LTEMatchExpression();
//             e->init( path(), _rhs  );
//             return e;
//         }




}