"use strict";

var ComparisonMatchExpression = require('ComparisonMatchExpression');

// Autogenerated by cport.py on 2013-09-17 14:37
var LTEMatchExpression = module.exports = function LTEMatchExpression(){
	this._matchType = 'LTE';
}, klass = LTEMatchExpression, base =  ComparisonMatchExpression, proto = klass.prototype = Object.create(base.prototype, {constructor:{value:klass}});

/**
 * 
 * This documentation was automatically generated. Please update when you touch this function.
 * @method shallowClone
 * @param
 *
 */
proto.shallowClone = function shallowClone( /*  */ ){
// File: expression_leaf.h lines: 108-111
        var e = new LTEMatchExpression();
	e.init( this.path(), this._rhs );
	return e;
};

