"use strict";

// Autogenerated by cport.py on 2013-09-17 14:37
var MatchDetails = module.exports = function (){
	// File: match_details.cpp lines: 27-29
	this._elemMatchKeyRequested = false;
	this.resetOutput();
}, klass = MatchDetails, base =  Object  , proto = klass.prototype = Object.create(base.prototype, {constructor:{value:klass}});

// File: match_details.h lines: 60-60
proto._elemMatchKey = undefined;

// File: match_details.h lines: 59-59
proto._elemMatchKeyRequested = undefined;

// File: match_details.h lines: 58-58
proto._loadedRecord = undefined;

/**
 *
 * This documentation was automatically generated. Please update when you touch this function.
 * @method elemMatchKey
 * @param
 *
 */
proto.elemMatchKey = function elemMatchKey(){
	// File: match_details.cpp lines: 41-43
	if (!this.hasElemMatchKey()) throw new Error("no elem match key MatchDetails:29");
	return this._elemMatchKey.get();
};

/**
 *
 * This documentation was automatically generated. Please update when you touch this function.
 * @method hasElemMatchKey
 * @param
 *
 */
proto.hasElemMatchKey = function hasElemMatchKey(){
	// File: match_details.cpp lines: 37-38
	return this._elemMatchKey;
};

/**
 *
 * This documentation was automatically generated. Please update when you touch this function.
 * @method hasLoadedRecord
 * @param
 *
 */
proto.hasLoadedRecord = function hasLoadedRecord(){
	// File: match_details.h lines: 41-40
	return this._loadedRecord;
};

/**
 *
 * This documentation was automatically generated. Please update when you touch this function.
 * @method needRecord
 * @param
 *
 */
proto.needRecord = function needRecord(){
	// File: match_details.h lines: 45-44
	return this._elemMatchKeyRequested;
};

/**
 *
 * This documentation was automatically generated. Please update when you touch this function.
 * @method requestElemMatchKey
 * @param
 *
 */
proto.requestElemMatchKey = function requestElemMatchKey(){
	// File: match_details.h lines: 50-49
	this._elemMatchKeyRequested = true;
};

/**
 *
 * This documentation was automatically generated. Please update when you touch this function.
 * @method resetOutput
 * @param
 *
 */
proto.resetOutput = function resetOutput(){
	// File: match_details.cpp lines: 32-34
	this._loadedRecord = false;
	this._elemMatchKey = undefined;
};

/**
 *
 * This documentation was automatically generated. Please update when you touch this function.
 * @method setElemMatchKey
 * @param
 *
 */
proto.setElemMatchKey = function setElemMatchKey(elemMatchKey){
	// File: match_details.cpp lines: 46-49
	if ( this._elemMatchKeyRequested ) {
		this._elemMatchKey = elemMatchKey;
	}
};

/**
 *
 * This documentation was automatically generated. Please update when you touch this function.
 * @method setLoadedRecord
 * @param
 *
 */
proto.setLoadedRecord = function setLoadedRecord(loadedRecord){
	// File: match_details.h lines: 39-38
	this._loadedRecord = loadedRecord;
};

/**
 *
 * This documentation was automatically generated. Please update when you touch this function.
 * @method toString
 * @param
 *
 */
proto.toString = function toString(){
	// File: match_details.cpp lines: 52-57
	return "loadedRecord: " + this._loadedRecord + " " + "elemMatchKeyRequested: " + this._elemMatchKeyRequested + " " + "elemMatchKey: " + ( this._elemMatchKey ? this._elemMatchKey : "NONE" ) + " ";
};
