"use strict"



// Autogenerated by cport.py on 2013-09-17 14:37
var MatchableDocument = module.exports = function (){

}, klass = MatchableDocument, base =  Object  , proto = klass.prototype = Object.create(base.prototype, {constructor:{value:klass}});





/**
 * 
 * This documentation was automatically generated. Please update when you touch this function.
 * @method ~MatchableDocument
 * @param
 *
 */
proto.~MatchableDocument = function ~MatchableDocument( /*  */ ){

// File: matchable.cpp lines: 25-25
//     MatchableDocument::~MatchableDocument(){
//     }



}