"use strict"



// Autogenerated by cport.py on 2013-09-17 14:37
var OrMatchExpression = module.exports = function (){

}, klass = OrMatchExpression, base =  Object  , proto = klass.prototype = Object.create(base.prototype, {constructor:{value:klass}});





/**
 * 
 * This documentation was automatically generated. Please update when you touch this function.
 * @method OrMatchExpression
 * @param
 *
 */
proto.OrMatchExpression = function OrMatchExpression( /*  OR  */ ){
// File: expression_tree.h lines: 80-79
//         OrMatchExpression() : ListOfMatchExpression( OR ){}




}


/**
 * 
 * This documentation was automatically generated. Please update when you touch this function.
 * @method debugString
 * @param
 *
 */
proto.debugString = function debugString( /*  StringBuilder& debug, int level  */ ){

// File: expression_tree.cpp lines: 112-115
//     void OrMatchExpression::debugString( StringBuilder& debug, int level ) const {
//         _debugAddSpace( debug, level );
//         debug << "$or\n";
//         _debugList( debug, level );
//     }



}


/**
 * 
 * This documentation was automatically generated. Please update when you touch this function.
 * @method matches
 * @param
 *
 */
proto.matches = function matches( /*  const MatchableDocument* doc, MatchDetails* details  */ ){

// File: expression_tree.cpp lines: 93-99
//     bool OrMatchExpression::matches( const MatchableDocument* doc, MatchDetails* details ) const {
//         for ( size_t i = 0; i < numChildren(); i++ ) {
//             if ( getChild(i)->matches( doc, NULL ) ) {
//                 return true;
//             }
//         }
//         return false;
//     }



}


/**
 * 
 * This documentation was automatically generated. Please update when you touch this function.
 * @method matchesSingleElement
 * @param
 *
 */
proto.matchesSingleElement = function matchesSingleElement( /*  const BSONElement& e  */ ){

// File: expression_tree.cpp lines: 102-108
//     bool OrMatchExpression::matchesSingleElement( const BSONElement& e ) const {
//         for ( size_t i = 0; i < numChildren(); i++ ) {
//             if ( getChild(i)->matchesSingleElement( e ) ) {
//                 return true;
//             }
//         }
//         return false;
//     }



}


/**
 * 
 * This documentation was automatically generated. Please update when you touch this function.
 * @method shallowClone
 * @param
 *
 */
proto.shallowClone = function shallowClone( /*  */ ){
// File: expression_tree.h lines: 86-91
//         virtual MatchExpression* shallowClone() const {
//             OrMatchExpression* self = new OrMatchExpression();
//             for (size_t i = 0; i < numChildren(); ++i) {
//                 self->add(getChild(i)->shallowClone());
//             }
//             return self;
//         }




}


/**
 * 
 * This documentation was automatically generated. Please update when you touch this function.
 * @method ~OrMatchExpression
 * @param
 *
 */
proto.~OrMatchExpression = function ~OrMatchExpression( /*  */ ){
// File: expression_tree.h lines: 81-80
//         virtual ~OrMatchExpression(){}




}