"use strict"



// Autogenerated by cport.py on 2013-09-17 14:37
var TagData = module.exports = function (){

}, klass = TagData, base =  Object  , proto = klass.prototype = Object.create(base.prototype, {constructor:{value:klass}});





/**
 * 
 * This documentation was automatically generated. Please update when you touch this function.
 * @method ~TagData
 * @param
 *
 */
proto.~TagData = function ~TagData( /*  */ ){
// File: expression.h lines: 151-150
//             virtual ~TagData() { }




}