"use strict";



// Autogenerated by cport.py on 2013-09-17 14:37
var TagData = module.exports = function TagData (){

}, klass = TagData, base =  Object  , proto = klass.prototype = Object.create(base.prototype, {constructor:{value:klass}});





/**
 * debugString pure virtual.
 *
 * @method debugString
 *
 */
proto.debugString = function debugString() {
	throw new Error('Virtual function called.');
};

// Below this line is manually generated based on inferred info in the source.

/**
 * resets the tag data.
 *
 *@method reset
 */
proto.reset = function reset( data ) {
	this._data = data;
};

/**
 * Sets the data tag
 * @method set
 * @param data
 */
proto.set = function set( data ) {
	this._data = data;
};



/**
 * Gets the data tag
 *
 * @method get
 *
 */
proto.get = function get(){
	return this._data;
};

